#+TITLE: org-ghi README

* Overview
  ~org-ghi~ provides a way of importing and syncing with GitHub issues
  from Org-mode. 

* Installation
  Download ~org-ghi~ from github

  : git clone https://github.com/punchagan/org-ghi.git
  
  Add the ~org-ghi~ directory to your load path and then add

  : (setq load-path (cons "~/.emacs.d/org-ghi/" load-path))
  : (require 'org-ghi)

  to your dot emacs.  
*** Dependencies
    1. org-ghi depends on /json/ which is a part of Emacs from v24. If
       you are using an older version of Emacs, you'll need to obtain
       it. 

    2. ~org-ghi~ may not work with old versions of org-mode. 

* Usage
  ~org-ghi-sync-all~ is your starting point into using ~org-ghi~.  It
  will fetch all the issues and add them to your chosen file, as TODO
  items.  If the issue has a milestone, the due date of the milestone
  is added as a deadline for the TODO.  The labels of the issue, get
  added as tags. 

  You can then work on your TODO and update your Issue from org-mode,
  by using ~org-ghi-update-current-issue~.  

  To create a new issue, Create a new TODO item; The TODO item should
  have the property ~:REPO:~ set to ~user/repo~.  Now use the function
  ~org-ghi-make-todo-an-issue~ to create a new issue. 
* Warning
  The interface is built upon GitHub's API v3 and it seems to be
  pretty fragile, with quite a few problems. Hence, this interface
  is pretty fragile, too...
* TO-DO
*** Let issues be filed under Milestones
*** body of Issue (API broken?)
*** Comments
